FROM golang:1.26-alpine3.24

RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
    --mount=type=cache,target=/var/lib/apk,sharing=locked \
    apk add --no-cache \
        "build-base=0.5-r4" \
        "libheif-dev=1.23.0-r0" \
        "ffmpeg=8.1.2-r0"

WORKDIR /app

RUN --mount=type=cache,target=/go/pkg/mod \
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.30.0 && \
    go install github.com/air-verse/air@v1.63.1

CMD ["air", "-c", ".air.toml"]
